# Generated by Django 5.2 on 2025-05-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_alter_contact_picture_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
